# -*- coding: utf-8 -*-
"""
build_lexicon.py — OFFLINE build tool for צלילון (NOT shipped in the game).

PHONEME model: each consonant's SOUND is derived from the niqqud (dagesh /
shin-sin dot), homophones are merged, and matres-lectionis (silent/vowel ו/י/ה)
are skipped. The position index is keyed by phoneme, not base letter.

Pipeline:
  1. read tools/words.py (generated by merge_lexicon.py; vocalized)
  2. compute the phoneme position index (FIRST/MIDDLE/LAST per sound)
  3. validate, build the per-(phoneme, position) coverage matrix, flag dead cells
  4. emit ../lexicon.json (minified) + ./coverage.md, and inject into template -> ../index.html

Run:  python3 tools/build_lexicon.py
"""

import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import words as W  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# ---- niqqud constants ----
NIQQUD = re.compile(r"[֑-ׇ]")
HEB_LETTER = re.compile(r"[א-ת]")
FOLD = {"ך": "כ", "ם": "מ", "ן": "נ", "ף": "פ", "ץ": "צ"}
DAG, SHIN, SIN = "ּ", "ׁ", "ׂ"
HOLAMS = {"ֹ", "ֺ"}
VOWELP = {chr(c) for c in range(0x05B0, 0x05BC)} | {chr(0x05C7)}
HIRIQ, TSERE = "ִ", "ֵ"
def _isniq(c): return "֑" <= c <= "ׇ"

# letter -> phoneme (unambiguous / merged consonants)
SIMPLE = {"ס": "S", "ת": "T", "ט": "T", "ק": "K", "ח": "X",
          "ג": "G", "ד": "D", "ז": "Z", "ל": "L", "מ": "M",
          "נ": "N", "צ": "TS", "ר": "R", "א": "GLOTTAL", "ע": "GLOTTAL"}

# the 20 phonemes (display order) + the letters that feed each (for the picker/UI)
PHONEMES = ["GLOTTAL", "B", "V", "G", "D", "H", "Z", "X", "T", "Y",
            "K", "L", "M", "N", "S", "P", "F", "TS", "R", "SH"]
SOURCES = {"GLOTTAL": "א/ע", "B": "בּ", "V": "ב/ו", "G": "ג", "D": "ד", "H": "ה",
           "Z": "ז", "X": "ח/כ", "T": "ט/ת", "Y": "י", "K": "כּ/ק", "L": "ל",
           "M": "מ", "N": "נ", "S": "ס/שׂ", "P": "פּ", "F": "פ", "TS": "צ",
           "R": "ר", "SH": "שׁ"}
POSITIONS = ["FIRST", "MIDDLE", "LAST"]
GN_OF_KEY = {"ms": ("m", "sg"), "fs": ("f", "sg"), "mp": ("m", "pl"), "fp": ("f", "pl")}
KEY_OF_GN = {v: k for k, v in GN_OF_KEY.items()}

MIN_LEN = 2
WARNINGS = []

# A geresh (ג׳ /dʒ/, צ׳ /tʃ/, ז׳ /ʒ/) turns a Hebrew consonant into a FOREIGN
# loanword sound that is NOT one of the 20 native phonemes — so the gimel/tzadi
# must not be matched as native /G//TS/, and TTS can't voice it (it reads the
# mark aloud). Drop any vocalized form carrying a geresh-family mark outright.
# U+0027 ' · U+2019 ’ · U+02BC ʼ · U+2032 ′ · U+05F3 ׳ geresh · U+05F4 ״ gershayim · U+0022 "
GERESH = {"'", "’", "ʼ", "′", "׳", "״", '"'}


def has_geresh(s):
    return any(c in GERESH for c in s)


def strip_niqqud(s):
    return NIQQUD.sub("", s)


def stripped_len(form):
    return len(HEB_LETTER.findall(strip_niqqud(form)))


def sound_of(base, m, is_first, is_last, prev):
    """Phoneme of one consonant occurrence (or None for matres/silent)."""
    if base == "ב": return "B" if DAG in m else "V"
    if base == "כ": return "K" if DAG in m else "X"
    if base == "פ": return "P" if DAG in m else "F"
    if base == "ש": return "SH" if SHIN in m else ("S" if SIN in m else None)
    if base in SIMPLE: return SIMPLE[base]
    if base == "ה":
        return None if (is_last and DAG not in m) else "H"     # silent final he
    if base == "ו":
        if HOLAMS & set(m): return None                        # holam-male (vowel)
        if DAG in m: return None                               # shuruk (vowel)
        if VOWELP & set(m): return "V"                         # voweled -> consonant
        return "V" if is_first else None                       # word-start vav, else mater
    if base == "י":
        if VOWELP & set(m): return "Y"
        if is_first: return "Y"
        if (HIRIQ in prev) or (TSERE in prev): return None     # hiriq/tsere-male (vowel)
        return "Y"                                             # diphthong glide ...ַי
    return None


def build_forms(forms):
    """{ms,fs,mp,fp: {w, idx}} for a 4-tuple of vocalized surface forms."""
    return {key: {"w": form, "idx": phoneme_index(form)}
            for key, form in zip(("ms", "fs", "mp", "fp"), forms)}


def phoneme_index(w):
    """{phoneme: [positions...]} for a vocalized surface form."""
    ch = list(w)
    n = len(ch)
    idx = {}
    i = 0
    prev = ""
    while i < n:
        c = ch[i]
        base = FOLD.get(c, c)
        if not HEB_LETTER.match(base):
            i += 1
            continue
        j = i + 1
        mk = ""
        while j < n and _isniq(ch[j]):
            mk += ch[j]
            j += 1
        s = sound_of(base, mk, i == 0, j >= n, prev)
        if s:
            pos = "FIRST" if i == 0 else ("LAST" if j >= n else "MIDDLE")
            idx.setdefault(s, [])
            if pos not in idx[s]:
                idx[s].append(pos)
        prev = mk
        i = j
    return idx


# ---------------------------------------------------------------------------
# build + validate
# ---------------------------------------------------------------------------
def build():
    nouns, adjectives, verbs = [], [], []

    for (w, g, num) in W.NOUNS:
        if has_geresh(w):
            WARNINGS.append(f"NOUN dropped (geresh/foreign sound): {w}"); continue
        if stripped_len(w) < MIN_LEN:
            WARNINGS.append(f"NOUN dropped (len<{MIN_LEN}): {w}"); continue
        if g not in ("m", "f") or num not in ("sg", "pl"):
            WARNINGS.append(f"NOUN bad tags: {w}"); continue
        nouns.append({"w": w, "g": g, "n": num, "idx": phoneme_index(w)})

    for forms in W.ADJECTIVES:
        if len(forms) != 4 or any(not f for f in forms):
            WARNINGS.append(f"ADJ needs 4 forms: {forms}"); continue
        if any(has_geresh(f) for f in forms):
            WARNINGS.append(f"ADJ dropped (geresh/foreign sound): {forms}"); continue
        if min(stripped_len(f) for f in forms) < MIN_LEN:
            WARNINGS.append(f"ADJ form too short: {forms}"); continue
        adjectives.append({"forms": build_forms(forms)})

    for row in W.VERBS:
        if len(row) != 5:
            WARNINGS.append(f"VERB needs (ms,fs,mp,fp,trans): {row}"); continue
        ms, fs, mp, fp, trans = row
        forms = (ms, fs, mp, fp)
        if any(has_geresh(f) for f in forms):
            WARNINGS.append(f"VERB dropped (geresh/foreign sound): {row}"); continue
        if any(not f for f in forms) or min(stripped_len(f) for f in forms) < MIN_LEN:
            WARNINGS.append(f"VERB bad/short: {row}"); continue
        verbs.append({"trans": bool(trans), "forms": build_forms(forms)})

    return {"nouns": nouns, "adjectives": adjectives, "verbs": verbs}


# ---------------------------------------------------------------------------
# coverage (phoneme x position) + demo
# ---------------------------------------------------------------------------
def matches(idx, ph, positions):
    # The word must carry the sound AND only at the selected position(s): a word
    # whose phoneme also occurs at an UNSELECTED position is rejected. e.g. /L/ at
    # LAST excludes צְלִיל (L at MIDDLE+LAST) — the kid practices the sound at the
    # chosen slot, so a stray occurrence elsewhere would be off-target/confusing.
    p = idx.get(ph)
    return bool(p) and all(x in positions for x in p)


def coverage(lex):
    matrix = {}
    for ph in PHONEMES:
        for P in POSITIONS:
            ps = [P]
            noun_gn = {gn: 0 for gn in GN_OF_KEY.values()}; n_total = 0
            for e in lex["nouns"]:
                if matches(e["idx"], ph, ps):
                    noun_gn[(e["g"], e["n"])] += 1; n_total += 1
            adj_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            for e in lex["adjectives"]:
                for key, gn in GN_OF_KEY.items():
                    if matches(e["forms"][key]["idx"], ph, ps): adj_gn[gn] += 1
            verb_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            verb_tr_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            for e in lex["verbs"]:
                for key, gn in GN_OF_KEY.items():
                    if matches(e["forms"][key]["idx"], ph, ps):
                        verb_gn[gn] += 1
                        if e["trans"]: verb_tr_gn[gn] += 1
            a_ok = any(noun_gn[g] and adj_gn[g] and verb_gn[g] for g in GN_OF_KEY.values())
            b_ok = (n_total >= 2) and any(noun_gn[g] and verb_tr_gn[g] for g in GN_OF_KEY.values())
            matrix[(ph, P)] = {"n": n_total, "a": sum(adj_gn.values()),
                               "v": sum(verb_gn.values()), "ok": a_ok or b_ok}
    return matrix


def gen_samples(lex, ph, position, limit=5):
    ps = [position]
    nouns = [e for e in lex["nouns"] if matches(e["idx"], ph, ps)]
    out, seen = [], set()

    def adjf(gn):
        k = KEY_OF_GN[gn]
        return [e["forms"][k]["w"] for e in lex["adjectives"] if matches(e["forms"][k]["idx"], ph, ps)]

    def verbf(gn, trans_only=False):
        k = KEY_OF_GN[gn]
        return [e["forms"][k]["w"] for e in lex["verbs"]
                if (not trans_only or e["trans"]) and matches(e["forms"][k]["idx"], ph, ps)]

    def add(words, t):
        if " ".join(words) not in seen and len(set(words)) == len(words):
            seen.add(" ".join(words)); out.append((" ".join(words), t))

    for subj in nouns:
        gn = (subj["g"], subj["n"])
        adjs, verbs = adjf(gn), verbf(gn)
        tverbs = verbf(gn, True)
        objs = [o["w"] for o in nouns if o["w"] != subj["w"]]
        if adjs and verbs: add([subj["w"], adjs[0], verbs[0]], "A")
        if adjs and tverbs and objs: add([subj["w"], adjs[0], tverbs[0], objs[0]], "C")
        if tverbs and objs: add([subj["w"], tverbs[0], objs[0]], "B")
        if len(out) >= limit: break
    return out[:limit]


def surface_form_count(lex):
    return len(lex["nouns"]) + 4 * len(lex["adjectives"]) + 4 * len(lex["verbs"])


def write_coverage_md(matrix, lex):
    lines = ["# Coverage matrix — phoneme model\n",
             f"_{len(lex['nouns'])} nouns · {len(lex['adjectives'])} adjectives · {len(lex['verbs'])} verbs._\n"]
    feasible = sum(1 for v in matrix.values() if v["ok"])
    word_feasible = sum(1 for v in matrix.values() if v["n"] >= 1)
    lines.append(f"**Sentence-feasible cells: {feasible}/{len(matrix)}**  ·  "
                 f"**Word-feasible cells (≥1 noun): {word_feasible}/{len(matrix)}**\n")
    word_only = [f"{ph}/{P}" for (ph, P), v in matrix.items() if v["n"] >= 1 and not v["ok"]]
    if word_only:
        lines.append("Word-only (no full sentence): " + ", ".join(word_only) + "\n")
    lines.append("| צליל | אותיות | תחילה | אמצע | סוף |")
    lines.append("|---|---|---|---|---|")
    for ph in PHONEMES:
        row = [ph, SOURCES[ph]]
        for P in POSITIONS:
            c = matrix[(ph, P)]
            row.append(("✓ " if c["ok"] else "✗ ") + f"{c['n']}n{c['a']}a{c['v']}v")
        lines.append("| " + " | ".join(row) + " |")
    dead = [f"{ph}/{P}" for (ph, P), v in matrix.items() if not v["ok"]]
    lines.append("\n## Dead cells\n" + (", ".join(dead) if dead else "(none)") + "\n")
    with open(os.path.join(HERE, "coverage.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


FAQ_H3P = re.compile(r"<h3>(.*?)</h3>\s*<p>(.*?)</p>", re.S)


def check_faq_parity(tmpl):
    """HARD build gate: the visible <details class="about"> FAQ Q/A must stay
    byte-identical to the FAQPage JSON-LD mainEntity. Google flags mismatched FAQ
    schema as spam, so a drift ABORTS the build before index.html is written. The
    test oracle (test_lexicon.py) can't catch this — it checks lexicon.json, not the
    HTML — so this is the only automated guard. Compares rendered text (HTML entities
    unescaped) pairwise and by count."""
    m = re.search(r'<script type="application/ld\+json">(.*?)</script>', tmpl, re.S)
    if not m:
        WARNINGS.append("no JSON-LD block found — skipped FAQ parity check")
        return
    graph = json.loads(m.group(1)).get("@graph", [])
    faq = next((n for n in graph if n.get("@type") == "FAQPage"), None)
    jsonld = [(q["name"], q["acceptedAnswer"]["text"])
              for q in (faq.get("mainEntity", []) if faq else [])]

    am = re.search(r'<details class="about".*?</details>', tmpl, re.S)
    visible = [(html.unescape(q.strip()), html.unescape(a.strip()))
               for q, a in FAQ_H3P.findall(am.group(0) if am else "")]

    if not jsonld and not visible:
        WARNINGS.append("no FAQ found in JSON-LD or <details class=about>")
        return

    errs = []
    if len(jsonld) != len(visible):
        errs.append(f"count differs: {len(jsonld)} in FAQPage JSON-LD vs {len(visible)} visible <h3>/<p>")
    for i in range(min(len(jsonld), len(visible))):
        (jq, ja), (vq, va) = jsonld[i], visible[i]
        if jq != vq:
            errs.append(f"[{i}] question differs:\n      JSON-LD: {jq!r}\n      visible: {vq!r}")
        if ja != va:
            errs.append(f"[{i}] answer differs:\n      JSON-LD: {ja!r}\n      visible: {va!r}")
    if errs:
        print("\nBUILD ABORTED — FAQ JSON-LD <-> visible <details> drift (spam risk):", file=sys.stderr)
        for e in errs:
            print("   - " + e, file=sys.stderr)
        sys.exit(1)


def main():
    lex = build()
    matrix = coverage(lex)
    # ship the phoneme tables + feasibility matrix the UI needs, so build_lexicon.py
    # stays the single source of truth (template.html reads these from LEX.meta).
    meta = {
        "phonemes": PHONEMES,
        "sources": SOURCES,
        "positions": POSITIONS,
        # feas = a full SENTENCE can be built (agreement across noun+adj+verb).
        # feasWord = single-word drill: >=1 noun whose target sound is confined to the cell.
        # feasWord is a SUPERSET of feas (a sentence always needs a confined noun subject),
        # so a sentence-dead cell can still be word-feasible — the picker gates each mode separately.
        "feas": {ph: {P: matrix[(ph, P)]["ok"] for P in POSITIONS} for ph in PHONEMES},
        "feasWord": {ph: {P: matrix[(ph, P)]["n"] >= 1 for P in POSITIONS} for ph in PHONEMES},
    }

    minified = json.dumps({**lex, "meta": meta}, ensure_ascii=False, separators=(",", ":"))
    with open(os.path.join(ROOT, "lexicon.json"), "w", encoding="utf-8") as f:
        f.write(minified)
    size_kb = os.path.getsize(os.path.join(ROOT, "lexicon.json")) / 1024

    index_kb = None
    tmpl_path = os.path.join(HERE, "template.html")
    if os.path.exists(tmpl_path):
        tmpl = open(tmpl_path, encoding="utf-8").read()
        if "__LEXICON_JSON__" not in tmpl:
            WARNINGS.append("template.html has no __LEXICON_JSON__ placeholder")
        check_faq_parity(tmpl)  # hard gate: abort if FAQ schema <-> visible <details> drift
        with open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8") as f:
            f.write(tmpl.replace("__LEXICON_JSON__", minified))
        index_kb = os.path.getsize(os.path.join(ROOT, "index.html")) / 1024

    write_coverage_md(matrix, lex)
    feasible = sum(1 for v in matrix.values() if v["ok"])
    word_feasible = sum(1 for v in matrix.values() if v["n"] >= 1)

    print("=" * 66)
    print(f"BUILD  nouns={len(lex['nouns'])} adj={len(lex['adjectives'])} verbs={len(lex['verbs'])} "
          f"forms={surface_form_count(lex)}")
    print(f"  lexicon.json {size_kb:.1f} KB" + (f"   index.html {index_kb:.1f} KB" if index_kb else ""))
    print(f"  coverage {feasible}/{len(matrix)} sentence · {word_feasible}/{len(matrix)} word (phoneme×position)")
    if WARNINGS:
        print(f"  WARNINGS ({len(WARNINGS)}):")
        for w in WARNINGS[:20]: print("   -", w)

    print("\n" + "=" * 66)
    print(f"  {'sound':9}{'letters':9}{'FIRST':>13}{'MIDDLE':>13}{'LAST':>13}")
    for ph in PHONEMES:
        cells = []
        for P in POSITIONS:
            c = matrix[(ph, P)]
            cells.append(f"{'OK ' if c['ok'] else '-- '}{c['n']}n{c['a']}a{c['v']}v")
        print(f"  {ph:9}{SOURCES[ph]:9}{cells[0]:>13}{cells[1]:>13}{cells[2]:>13}")
    dead = [f"{ph}/{P}" for (ph, P), v in matrix.items() if not v["ok"]]
    print("\n  DEAD:", ", ".join(dead) if dead else "(none)")

    print("\n" + "=" * 66)
    print("DEMO SENTENCES")
    for ph, P in [("SH", "FIRST"), ("B", "FIRST"), ("K", "FIRST"), ("X", "MIDDLE"),
                  ("S", "FIRST"), ("T", "LAST")]:
        print(f"\n  /{ph}/ ({SOURCES[ph]}) · {P}:")
        for s, t in gen_samples(lex, ph, P, 4):
            print(f"    [{t}] {s}")
    print()


if __name__ == "__main__":
    main()
