# -*- coding: utf-8 -*-
"""
build_lexicon.py — OFFLINE build tool for אותיות מדברות (NOT shipped in the game).

PHONEME model: each consonant's SOUND is derived from the niqqud (dagesh /
shin-sin dot), homophones are merged, and matres-lectionis (silent/vowel ו/י/ה)
are skipped. The position index is keyed by phoneme, not base letter.

Pipeline:
  1. read tools/words.py (generated by merge_lexicon.py; vocalized)
  2. compute the phoneme position index (FIRST/MIDDLE/LAST per sound)
  3. validate, build the per-(phoneme, position) coverage matrix, flag dead cells
  4. emit ../lexicon.json (minified) + ./coverage.md, and inject into template -> ../index.html

Run:  python3 tools/build_lexicon.py
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import words as W  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# ---- niqqud constants ----
NIQQUD = re.compile(r"[֑-ׇ]")
HEB_LETTER = re.compile(r"[א-ת]")
FOLD = {"ך": "כ", "ם": "מ", "ן": "נ", "ף": "פ", "ץ": "צ"}
DAG, SHIN, SIN = "ּ", "ׁ", "ׂ"
HOLAMS = {"ֹ", "ֺ"}
VOWELP = {chr(c) for c in range(0x05B0, 0x05BC)} | {chr(0x05C7)}
HIRIQ, TSERE = "ִ", "ֵ"
def _isniq(c): return "֑" <= c <= "ׇ"

# letter -> phoneme (unambiguous / merged consonants)
SIMPLE = {"ס": "S", "ת": "T", "ט": "T", "ק": "K", "ח": "X",
          "ג": "G", "ד": "D", "ז": "Z", "ל": "L", "מ": "M",
          "נ": "N", "צ": "TS", "ר": "R", "א": "GLOTTAL", "ע": "GLOTTAL"}

# the 20 phonemes (display order) + the letters that feed each (for the picker/UI)
PHONEMES = ["GLOTTAL", "B", "V", "G", "D", "H", "Z", "X", "T", "Y",
            "K", "L", "M", "N", "S", "P", "F", "TS", "R", "SH"]
SOURCES = {"GLOTTAL": "א/ע", "B": "בּ", "V": "ב/ו", "G": "ג", "D": "ד", "H": "ה",
           "Z": "ז", "X": "ח/כ", "T": "ט/ת", "Y": "י", "K": "כּ/ק", "L": "ל",
           "M": "מ", "N": "נ", "S": "ס/שׂ", "P": "פּ", "F": "פ", "TS": "צ",
           "R": "ר", "SH": "שׁ"}
POSITIONS = ["FIRST", "MIDDLE", "LAST"]
GN_OF_KEY = {"ms": ("m", "sg"), "fs": ("f", "sg"), "mp": ("m", "pl"), "fp": ("f", "pl")}
KEY_OF_GN = {v: k for k, v in GN_OF_KEY.items()}

MIN_LEN = 2
WARNINGS = []


def strip_niqqud(s):
    return NIQQUD.sub("", s)


def stripped_len(form):
    return len(HEB_LETTER.findall(strip_niqqud(form)))


def sound_of(base, m, is_first, is_last, prev):
    """Phoneme of one consonant occurrence (or None for matres/silent)."""
    if base == "ב": return "B" if DAG in m else "V"
    if base == "כ": return "K" if DAG in m else "X"
    if base == "פ": return "P" if DAG in m else "F"
    if base == "ש": return "SH" if SHIN in m else ("S" if SIN in m else None)
    if base in SIMPLE: return SIMPLE[base]
    if base == "ה":
        return None if (is_last and DAG not in m) else "H"     # silent final he
    if base == "ו":
        if HOLAMS & set(m): return None                        # holam-male (vowel)
        if DAG in m: return None                               # shuruk (vowel)
        if VOWELP & set(m): return "V"                         # voweled -> consonant
        return "V" if is_first else None                       # word-start vav, else mater
    if base == "י":
        if VOWELP & set(m): return "Y"
        if is_first: return "Y"
        if (HIRIQ in prev) or (TSERE in prev): return None     # hiriq/tsere-male (vowel)
        return "Y"                                             # diphthong glide ...ַי
    return None


def phoneme_index(w):
    """{phoneme: [positions...]} for a vocalized surface form."""
    ch = list(w)
    n = len(ch)
    idx = {}
    i = 0
    prev = ""
    while i < n:
        c = ch[i]
        base = FOLD.get(c, c)
        if not HEB_LETTER.match(base):
            i += 1
            continue
        j = i + 1
        mk = ""
        while j < n and _isniq(ch[j]):
            mk += ch[j]
            j += 1
        s = sound_of(base, mk, i == 0, j >= n, prev)
        if s:
            pos = "FIRST" if i == 0 else ("LAST" if j >= n else "MIDDLE")
            idx.setdefault(s, [])
            if pos not in idx[s]:
                idx[s].append(pos)
        prev = mk
        i = j
    return idx


# ---------------------------------------------------------------------------
# build + validate
# ---------------------------------------------------------------------------
def build():
    nouns, adjectives, verbs = [], [], []

    for (w, g, num) in W.NOUNS:
        if stripped_len(w) < MIN_LEN:
            WARNINGS.append(f"NOUN dropped (len<{MIN_LEN}): {w}"); continue
        if g not in ("m", "f") or num not in ("sg", "pl"):
            WARNINGS.append(f"NOUN bad tags: {w}"); continue
        nouns.append({"w": w, "g": g, "n": num, "idx": phoneme_index(w)})

    for forms in W.ADJECTIVES:
        if len(forms) != 4 or any(not f for f in forms):
            WARNINGS.append(f"ADJ needs 4 forms: {forms}"); continue
        if min(stripped_len(f) for f in forms) < MIN_LEN:
            WARNINGS.append(f"ADJ form too short: {forms}"); continue
        entry = {"forms": {}}
        for key, form in zip(("ms", "fs", "mp", "fp"), forms):
            entry["forms"][key] = {"w": form, "idx": phoneme_index(form)}
        adjectives.append(entry)

    for row in W.VERBS:
        if len(row) != 5:
            WARNINGS.append(f"VERB needs (ms,fs,mp,fp,trans): {row}"); continue
        ms, fs, mp, fp, trans = row
        forms = (ms, fs, mp, fp)
        if any(not f for f in forms) or min(stripped_len(f) for f in forms) < MIN_LEN:
            WARNINGS.append(f"VERB bad/short: {row}"); continue
        entry = {"trans": bool(trans), "forms": {}}
        for key, form in zip(("ms", "fs", "mp", "fp"), forms):
            entry["forms"][key] = {"w": form, "idx": phoneme_index(form)}
        verbs.append(entry)

    return {"nouns": nouns, "adjectives": adjectives, "verbs": verbs}


# ---------------------------------------------------------------------------
# coverage (phoneme x position) + demo
# ---------------------------------------------------------------------------
def matches(idx, ph, positions):
    p = idx.get(ph)
    return bool(p) and any(x in positions for x in p)


def coverage(lex):
    matrix = {}
    for ph in PHONEMES:
        for P in POSITIONS:
            ps = [P]
            noun_gn = {gn: 0 for gn in GN_OF_KEY.values()}; n_total = 0
            for e in lex["nouns"]:
                if matches(e["idx"], ph, ps):
                    noun_gn[(e["g"], e["n"])] += 1; n_total += 1
            adj_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            for e in lex["adjectives"]:
                for key, gn in GN_OF_KEY.items():
                    if matches(e["forms"][key]["idx"], ph, ps): adj_gn[gn] += 1
            verb_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            verb_tr_gn = {gn: 0 for gn in GN_OF_KEY.values()}
            for e in lex["verbs"]:
                for key, gn in GN_OF_KEY.items():
                    if matches(e["forms"][key]["idx"], ph, ps):
                        verb_gn[gn] += 1
                        if e["trans"]: verb_tr_gn[gn] += 1
            a_ok = any(noun_gn[g] and adj_gn[g] and verb_gn[g] for g in GN_OF_KEY.values())
            b_ok = (n_total >= 2) and any(noun_gn[g] and verb_tr_gn[g] for g in GN_OF_KEY.values())
            matrix[(ph, P)] = {"n": n_total, "a": sum(adj_gn.values()),
                               "v": sum(verb_gn.values()), "ok": a_ok or b_ok}
    return matrix


def gen_samples(lex, ph, position, limit=5):
    ps = [position]
    nouns = [e for e in lex["nouns"] if matches(e["idx"], ph, ps)]
    out, seen = [], set()

    def adjf(gn):
        k = KEY_OF_GN[gn]
        return [e["forms"][k]["w"] for e in lex["adjectives"] if matches(e["forms"][k]["idx"], ph, ps)]

    def verbf(gn, trans_only=False):
        k = KEY_OF_GN[gn]
        return [e["forms"][k]["w"] for e in lex["verbs"]
                if (not trans_only or e["trans"]) and matches(e["forms"][k]["idx"], ph, ps)]

    def add(words, t):
        if " ".join(words) not in seen and len(set(words)) == len(words):
            seen.add(" ".join(words)); out.append((" ".join(words), t))

    for subj in nouns:
        gn = (subj["g"], subj["n"])
        adjs, verbs = adjf(gn), verbf(gn)
        tverbs = verbf(gn, True)
        objs = [o["w"] for o in nouns if o["w"] != subj["w"]]
        if adjs and verbs: add([subj["w"], adjs[0], verbs[0]], "A")
        if adjs and tverbs and objs: add([subj["w"], adjs[0], tverbs[0], objs[0]], "C")
        if tverbs and objs: add([subj["w"], tverbs[0], objs[0]], "B")
        if len(out) >= limit: break
    return out[:limit]


def surface_form_count(lex):
    return len(lex["nouns"]) + 4 * len(lex["adjectives"]) + 4 * len(lex["verbs"])


def write_coverage_md(matrix, lex):
    lines = ["# Coverage matrix — phoneme model\n",
             f"_{len(lex['nouns'])} nouns · {len(lex['adjectives'])} adjectives · {len(lex['verbs'])} verbs._\n"]
    feasible = sum(1 for v in matrix.values() if v["ok"])
    lines.append(f"**Feasible cells: {feasible}/{len(matrix)}**\n")
    lines.append("| צליל | אותיות | תחילה | אמצע | סוף |")
    lines.append("|---|---|---|---|---|")
    for ph in PHONEMES:
        row = [ph, SOURCES[ph]]
        for P in POSITIONS:
            c = matrix[(ph, P)]
            row.append(("✓ " if c["ok"] else "✗ ") + f"{c['n']}n{c['a']}a{c['v']}v")
        lines.append("| " + " | ".join(row) + " |")
    dead = [f"{ph}/{P}" for (ph, P), v in matrix.items() if not v["ok"]]
    lines.append("\n## Dead cells\n" + (", ".join(dead) if dead else "(none)") + "\n")
    with open(os.path.join(HERE, "coverage.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    lex = build()

    minified = json.dumps(lex, ensure_ascii=False, separators=(",", ":"))
    with open(os.path.join(ROOT, "lexicon.json"), "w", encoding="utf-8") as f:
        f.write(minified)
    size_kb = os.path.getsize(os.path.join(ROOT, "lexicon.json")) / 1024

    index_kb = None
    tmpl_path = os.path.join(HERE, "template.html")
    if os.path.exists(tmpl_path):
        tmpl = open(tmpl_path, encoding="utf-8").read()
        if "__LEXICON_JSON__" not in tmpl:
            WARNINGS.append("template.html has no __LEXICON_JSON__ placeholder")
        with open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8") as f:
            f.write(tmpl.replace("__LEXICON_JSON__", minified))
        index_kb = os.path.getsize(os.path.join(ROOT, "index.html")) / 1024

    matrix = coverage(lex)
    write_coverage_md(matrix, lex)
    feasible = sum(1 for v in matrix.values() if v["ok"])

    print("=" * 66)
    print(f"BUILD  nouns={len(lex['nouns'])} adj={len(lex['adjectives'])} verbs={len(lex['verbs'])} "
          f"forms={surface_form_count(lex)}")
    print(f"  lexicon.json {size_kb:.1f} KB" + (f"   index.html {index_kb:.1f} KB" if index_kb else ""))
    print(f"  coverage {feasible}/{len(matrix)} (phoneme×position) feasible")
    if WARNINGS:
        print(f"  WARNINGS ({len(WARNINGS)}):")
        for w in WARNINGS[:20]: print("   -", w)

    print("\n" + "=" * 66)
    print(f"  {'sound':9}{'letters':9}{'FIRST':>13}{'MIDDLE':>13}{'LAST':>13}")
    for ph in PHONEMES:
        cells = []
        for P in POSITIONS:
            c = matrix[(ph, P)]
            cells.append(f"{'OK ' if c['ok'] else '-- '}{c['n']}n{c['a']}a{c['v']}v")
        print(f"  {ph:9}{SOURCES[ph]:9}{cells[0]:>13}{cells[1]:>13}{cells[2]:>13}")
    dead = [f"{ph}/{P}" for (ph, P), v in matrix.items() if not v["ok"]]
    print("\n  DEAD:", ", ".join(dead) if dead else "(none)")

    print("\n" + "=" * 66)
    print("DEMO SENTENCES")
    for ph, P in [("SH", "FIRST"), ("B", "FIRST"), ("K", "FIRST"), ("X", "MIDDLE"),
                  ("S", "FIRST"), ("T", "LAST")]:
        print(f"\n  /{ph}/ ({SOURCES[ph]}) · {P}:")
        for s, t in gen_samples(lex, ph, P, 4):
            print(f"    [{t}] {s}")
    print()


if __name__ == "__main__":
    main()
